### ISSUE TITLE
Billing account fee issue

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#33] opened 2018-02-28 17:13 UTC
When calling the API to create/update fees, it seems that it's always requiring the user to pass in an array of fixed fees per challenge type even when they only want to set the BA to a % fee.

**Comment by ajefts** [comment] 2018-02-28 17:13
@skyhit Can you take a look at this when you get a chance please?

**Comment by skyhit** [comment] 2018-03-02 06:38
@ajefts the current logic is mimicing same logic in direct app, which looks like need to provide both.

I will check if we can simplify it

**Comment by ajefts** [comment] 2018-03-02 14:22
ok, thanks.  If we set it as a % fee, then we shouldn't require anything for the specific challenge type fees.

**Comment by skyhit** [comment] 2018-03-05 02:16
@ajefts is it related to #34 ?

**Comment by skyhit** [comment] 2018-03-05 04:59
@ajefts please confirm to launch for this - https://www.topcoder.com/direct/contest/detail?projectId=30063343

for challenge fees based on the each challenge type,  what if for some challenge types, the fees are not passed?

**Comment by ajefts** [comment] 2018-03-05 16:02
yes, this is related to #34

Looping in @cwdcwd since he's stepping in to help with a lot of the arch and dev management.  @cwdcwd Mind reviewing this one to make sure it looks ok?  This is an API used to set billing account fees, which is called from our salesforce org..

**Comment by mcards13** [comment] 2018-03-07 14:08
@cwdcwd @ajefts @skyhit - what is the timing on a resolution?

**Comment by skyhit** [comment] 2018-03-07 14:18
@mcards13 get confirmed from @cwdcwd I just kick it started, I was expected it to be finished in 3 days

**Comment by ajefts** [comment] 2018-03-07 15:32
> for challenge fees based on the each challenge type, what if for some challenge types, the fees are not passed?

@skyhit for that question, they should be set to $0 if no value is passed in.

**Comment by cwdcwd** [comment] 2018-03-07 16:20
![](https://github.trello.services/images/mini-trello-icon.png) [Billing account fee issue](https://trello.com/c/a5QgAC1f/1-billing-account-fee-issue)

**Comment by skyhit** [comment] 2018-03-08 08:37
@ajefts why not considering missing as 0 challenge fee?  to maintain a list of challenge types, like if new challenge types coming, is pretty hard.

**Comment by ajefts** [comment] 2018-03-08 12:06
I think we're saying the same thing.  The default value for fees that are not passed into the API would be $0.

**Comment by skyhit** [comment] 2018-03-08 12:13
@ajefts I mean whether we need to save it in database or not?  I think it should be handled logically (in program)

**Comment by ajefts** [comment] 2018-03-08 20:11
Agreed

**Comment by mcards13** [comment] 2018-03-12 15:10
@skyhit @ajefts @cwdcwd - What is the expected ETA to have a solution? - Thanks

**Comment by skyhit** [comment] 2018-03-12 15:13
@mcards13 @ajefts  @cwdcwd Sorry, I thought the review will be done in the weekend, but we are short of reviewers now, so the hangs a bit, but it will be ready tomorrow, I try to push to dev as quickly as I can for testing

**Comment by mcards13** [comment] 2018-03-12 15:15
thanks

**Comment by skyhit** [comment] 2018-03-14 01:02
@ajefts @mcards13 @cwdcwd here is the PR - https://github.com/topcoder-platform/tc-billing-account-service/pull/35, should we merge to dev branch to test in DEV environment?

**Comment by mcards13** [comment] 2018-03-16 13:06
@ajefts does this work for you?   I would like to get Sumit testing against it.

**Comment by cwdcwd** [comment] 2018-03-16 21:09
@skyhit merge and test please. Would like to close this out for @mcards13 immediately

**Closed as completed** 2018-03-18 01:47 UTC
